# Generated by Django 3.1.2 on 2020-12-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201224_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card',
            field=models.IntegerField(null=True),
        ),
    ]
