# Generated by Django 3.1.2 on 2020-12-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card',
            field=models.IntegerField(null=True),
        ),
    ]
