# Generated by Django 3.1.2 on 2020-12-28 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0043_auto_20201224_1358'),
        ('users', '0006_auto_20201226_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_cards',
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='usercards',
            field=models.ManyToManyField(related_name='cards_lst', through='users.UserCard', to='cards.Card'),
        ),
    ]
