# Generated by Django 3.1.2 on 2021-01-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0043_auto_20201224_1358'),
        ('users', '0007_auto_20201228_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercard',
            name='ordering',
        ),
        migrations.AddField(
            model_name='usercard',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='usercards',
            field=models.ManyToManyField(through='users.UserCard', to='cards.Card'),
        ),
    ]
