# Generated by Django 3.1.2 on 2021-01-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210110_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
