# Generated by Django 3.1.2 on 2021-01-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/static/default.jpg', upload_to='profile_pics'),
        ),
    ]
