# Generated by Django 3.1.2 on 2021-01-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210113_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='quantity_jp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercard',
            name='quantity_parallel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercard',
            name='quantity_parallel_jp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
