# Generated by Django 3.1.2 on 2021-01-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210129_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='quantity_jp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='quantity_parallel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='quantity_parallel_jp',
            field=models.IntegerField(default=0),
        ),
    ]
