# Generated by Django 3.0.4 on 2020-05-09 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='slug',
        ),
    ]
