# Generated by Django 3.0.4 on 2020-05-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20200508_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_en', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='attribute',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('Digimon', 'Digimon'), ('Tamer', 'Tamer'), ('Option', 'Option')], default='Digimon', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Green', 'Green')], default='Red', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='digimon_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='dp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='effect',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='evolution_cost_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='evolution_cost_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='evolutionary_effect',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='lv',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='play_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='stage',
            field=models.CharField(choices=[('Mega', 'Mega'), ('Ultimate', 'Ultimate'), ('Champion', 'Champion'), ('Rookie', 'Rookie'), ('Baby', 'Baby')], default='Rookie', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='set',
            field=models.ManyToManyField(blank=True, null=True, to='cards.Set'),
        ),
    ]
