# Generated by Django 3.0.4 on 2020-05-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20200509_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='artist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='title_jp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('Digimon', 'Digimon'), ('Digitama', 'Digitama'), ('Tamer', 'Tamer'), ('Option', 'Option')], default='Digimon', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Colorless', 'Colorless')], default='Red', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
