# Generated by Django 3.0.4 on 2020-05-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20200509_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(blank=True, choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('SR', 'Super Rare'), ('SEC', 'Secret Rare'), ('P', 'Promo')], default='Uncommon', max_length=100, null=True),
        ),
    ]
