# Generated by Django 3.0.4 on 2020-05-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20200509_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digimon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('stage', models.CharField(choices=[('Mega', 'Mega'), ('Ultimate', 'Ultimate'), ('Champion', 'Champion'), ('Rookie', 'Rookie'), ('Baby', 'Baby')], default='Rookie', max_length=20)),
                ('attribute', models.CharField(blank=True, max_length=100, null=True)),
                ('digimon_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='set',
            old_name='image_en',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='card',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='card',
            name='digimon_type',
        ),
        migrations.RemoveField(
            model_name='card',
            name='stage',
        ),
        migrations.AddField(
            model_name='card',
            name='evolution_cost_1_color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Colorless', 'Colorless')], default='Red', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='evolution_cost_2_color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Colorless', 'Colorless')], default='Red', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='digimon',
            field=models.ManyToManyField(blank=True, null=True, to='cards.Digimon'),
        ),
    ]
