# Generated by Django 3.0.4 on 2020-05-09 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20200509_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='digimon',
        ),
        migrations.AddField(
            model_name='card',
            name='digimon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.Digimon'),
        ),
        migrations.RemoveField(
            model_name='card',
            name='set',
        ),
        migrations.AddField(
            model_name='card',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.Set'),
        ),
    ]
