# Generated by Django 3.0.4 on 2020-05-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_auto_20200510_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='effect_keyword_1',
            field=models.CharField(blank=True, choices=[('Pierce', 'Pierce'), ('Blocker', 'Blocker'), ('Jamming', 'Jamming'), ('Draw 1', 'Draw 1'), ('Draw 2', 'Draw 2'), ('When Placed', 'When Placed'), ('Recovery +1 (Deck)', 'Recovery +1 (Deck)'), ('Security Attack +1', 'Security Attack +1'), ('Security Attack + 2', 'Security Attack + 2'), ('Security Attack - 3', 'Security Attack - 3')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='effect_keyword_2',
            field=models.CharField(blank=True, choices=[('Pierce', 'Pierce'), ('Blocker', 'Blocker'), ('Jamming', 'Jamming'), ('Draw 1', 'Draw 1'), ('Draw 2', 'Draw 2'), ('When Placed', 'When Placed'), ('Recovery +1 (Deck)', 'Recovery +1 (Deck)'), ('Security Attack +1', 'Security Attack +1'), ('Security Attack + 2', 'Security Attack + 2'), ('Security Attack - 3', 'Security Attack - 3')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='effect_keyword_3',
            field=models.CharField(blank=True, choices=[('Pierce', 'Pierce'), ('Blocker', 'Blocker'), ('Jamming', 'Jamming'), ('Draw 1', 'Draw 1'), ('Draw 2', 'Draw 2'), ('When Placed', 'When Placed'), ('Recovery +1 (Deck)', 'Recovery +1 (Deck)'), ('Security Attack +1', 'Security Attack +1'), ('Security Attack + 2', 'Security Attack + 2'), ('Security Attack - 3', 'Security Attack - 3')], max_length=100, null=True),
        ),
    ]
