# Generated by Django 3.0.4 on 2020-05-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_auto_20200510_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='digimon',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
