# Generated by Django 3.0.4 on 2020-05-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_auto_20200510_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image_en',
            field=models.ImageField(blank=True, upload_to='en/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image_jp',
            field=models.ImageField(blank=True, upload_to='jp/'),
        ),
    ]
