# Generated by Django 3.0.4 on 2020-05-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_auto_20200511_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='effect_keyword_int_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='effect_keyword_int_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='effect_keyword_int_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='evolutionary_effect_keyword_int_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='evolutionary_effect_keyword_int_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='evolutionary_effect_keyword_int_3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
