# Generated by Django 3.0.4 on 2020-05-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0020_auto_20200512_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='produc_image_1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='set',
            name='produc_image_2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='set',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='set_type',
            field=models.CharField(choices=[('Deck', 'Deck'), ('Booster', 'Booster'), ('Promo', 'Promo')], default='Deck', max_length=20),
        ),
        migrations.AddField(
            model_name='set',
            name='total_cards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='total_unique',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
