# Generated by Django 3.0.4 on 2020-05-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_auto_20200513_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='promo_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='promo_release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
