# Generated by Django 3.0.4 on 2020-05-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0023_auto_20200514_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='promo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
