# Generated by Django 3.0.4 on 2020-05-17 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0025_card_image_parallel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('Digitama', 'Digitama'), ('Digimon', 'Digimon'), ('Tamer', 'Tamer'), ('Option', 'Option')], default='Digimon', max_length=20),
        ),
        migrations.CreateModel(
            name='LastCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parallel', models.BooleanField()),
                ('set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.Card')),
            ],
        ),
    ]
