# Generated by Django 3.0.4 on 2020-05-17 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0026_auto_20200517_1958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LastCards',
            new_name='NewC',
        ),
    ]
