# Generated by Django 3.0.4 on 2020-05-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0027_auto_20200517_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newc',
            old_name='set',
            new_name='card',
        ),
    ]
