# Generated by Django 3.0.4 on 2020-05-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0028_auto_20200517_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='newc',
            name='card_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
