# Generated by Django 3.0.4 on 2020-05-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0029_newc_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newc',
            name='card_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
