# Generated by Django 3.0.4 on 2020-05-18 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0030_auto_20200517_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newc',
            name='card_number',
        ),
    ]
