# Generated by Django 3.0.4 on 2020-05-23 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0033_auto_20200522_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='content',
            field=models.TextField(blank=True, max_length=2255, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='releated_cards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.Card'),
        ),
        migrations.AddField(
            model_name='new',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
