# Generated by Django 3.0.4 on 2020-05-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0035_auto_20200523_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
