# Generated by Django 3.0.4 on 2020-05-23 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0036_new_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='slug',
        ),
    ]
