# Generated by Django 3.0.4 on 2020-06-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0037_remove_new_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Purple', 'Purple'), ('Black', 'Black'), ('Colorless', 'Colorless')], default='Red', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='evolution_cost_1_color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Purple', 'Purple'), ('Black', 'Black'), ('Colorless', 'Colorless')], default='Red', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='evolution_cost_2_color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Purple', 'Purple'), ('Black', 'Black'), ('Colorless', 'Colorless')], default='Red', max_length=20),
        ),
    ]
