# Generated by Django 3.1.2 on 2020-12-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0040_auto_20201214_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ebay',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='suruga_ya',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
