# Generated by Django 3.1.2 on 2020-12-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0041_auto_20201214_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='amazon_jp',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
