# Generated by Django 3.1.2 on 2021-01-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0043_auto_20201224_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image_parallel',
        ),
        migrations.AddField(
            model_name='card',
            name='image_parallel_en',
            field=models.ImageField(blank=True, upload_to='parallel-en/'),
        ),
        migrations.AddField(
            model_name='card',
            name='image_parallel_jp',
            field=models.ImageField(blank=True, upload_to='parallel-jp/'),
        ),
    ]
