# Generated by Django 3.1.2 on 2021-01-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0046_auto_20210113_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_blue', models.CharField(blank=True, max_length=100, null=True)),
                ('effect_purple', models.CharField(blank=True, max_length=100, null=True)),
                ('effect_txt', models.TextField(blank=True, null=True)),
                ('effect_keyword', models.CharField(blank=True, choices=[('Pierce', 'Pierce'), ('Blocker', 'Blocker'), ('Jamming', 'Jamming'), ('Draw', 'Draw'), ('Recovery (Deck) +', 'Recovery (Deck) +'), ('Security Attack +', 'Security Attack +'), ('Security Attack -', 'Security Attack -'), ('Vengeance', 'Vengeance'), ('Download', 'Download'), ('De-Digivolve', 'De-Digivolve')], max_length=100, null=True)),
                ('effect_keyword_int', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='effect',
            field=models.ManyToManyField(blank=True, to='cards.Effect'),
        ),
    ]
