# Generated by Django 3.1.2 on 2021-01-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0047_auto_20210121_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='effect',
        ),
        migrations.AddField(
            model_name='card',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.effect'),
        ),
    ]
