# Generated by Django 3.1.2 on 2021-01-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0048_auto_20210121_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='effect',
        ),
        migrations.AddField(
            model_name='card',
            name='effect',
            field=models.ManyToManyField(blank=True, to='cards.Effect'),
        ),
    ]
