# Generated by Django 3.1.2 on 2021-01-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0049_auto_20210121_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effect',
            name='effect_keyword',
        ),
        migrations.AddField(
            model_name='effect',
            name='effect_type',
            field=models.CharField(blank=True, choices=[('Main', 'Main'), ('Inheritable', 'Inheritable')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='effect_blue',
            field=models.CharField(blank=True, choices=[('Main', 'Main'), ('Security', 'Security'), ('Your Turn', 'Your Turn'), ('On Play', 'On Play'), ('When Attacking', 'When Attacking'), ('When Digivolving', 'When Digivolving'), ('Start of Your Turn', 'Start of Your Turn'), ("Opponent's Turn", "Opponent's Turn"), ('On Deletion', 'On Deletion'), ('End of Attack', 'End of Attack'), ('All Turns', 'All Turns'), ("End of Opponent's Turn", "End of Opponent's Turn"), ('Both Turns', 'Both Turns')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='effect_purple',
            field=models.CharField(blank=True, choices=[('Once Per Turn', 'Once Per Turn'), ('Twice Per Turn', 'Twice Per Turn')], max_length=100, null=True),
        ),
    ]
