# Generated by Django 3.1.2 on 2021-01-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0052_auto_20210121_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='artist_parallel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
