# Generated by Django 3.1.2 on 2021-01-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0053_card_artist_parallel'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='translated',
            field=models.BooleanField(null=True),
        ),
    ]
