# Generated by Django 3.1.2 on 2021-01-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0054_card_translated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='translated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
