# Generated by Django 3.1.2 on 2021-01-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0055_auto_20210122_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='artist_parallel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='translated',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
    ]
