# Generated by Django 3.1.2 on 2021-01-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0057_auto_20210123_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='price_1',
        ),
        migrations.RemoveField(
            model_name='set',
            name='price_2',
        ),
        migrations.AddField(
            model_name='set',
            name='color_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='color_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
