# Generated by Django 3.1.2 on 2021-01-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0058_auto_20210126_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='effect_txt_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
