# Generated by Django 3.1.2 on 2021-01-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0059_effect_effect_txt_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='effect_type',
            field=models.CharField(choices=[('Main', 'Main'), ('Inheritable', 'Inheritable')], default='Main', max_length=100),
        ),
    ]
