# Generated by Django 3.1.2 on 2021-03-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0060_auto_20210130_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='effect_keyword_int_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
