# Generated by Django 3.1.2 on 2021-03-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0061_effect_effect_keyword_int_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_jp', models.ImageField(blank=True, upload_to='parallel-jp/')),
                ('image_en', models.ImageField(blank=True, upload_to='parallel-en/')),
                ('artist', models.CharField(blank=True, max_length=100, null=True)),
                ('effect_txt', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='artist_parallel',
        ),
        migrations.RemoveField(
            model_name='card',
            name='image_parallel_en',
        ),
        migrations.RemoveField(
            model_name='card',
            name='image_parallel_jp',
        ),
        migrations.AlterField(
            model_name='digimon',
            name='stage',
            field=models.CharField(choices=[('Mega', 'Mega'), ('Ultimate', 'Ultimate'), ('Champion', 'Champion'), ('Rookie', 'Rookie'), ('In-Training', 'In-Training'), ('Hybrid', 'Hybrid')], default='Rookie', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='alternate_art',
            field=models.ManyToManyField(blank=True, to='cards.AlternateArt'),
        ),
    ]
