# Generated by Django 3.1.2 on 2021-03-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0062_auto_20210330_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternateart',
            old_name='effect_txt',
            new_name='txt',
        ),
        migrations.RemoveField(
            model_name='card',
            name='amazon_jp',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ebay',
        ),
        migrations.RemoveField(
            model_name='card',
            name='suruga_ya',
        ),
        migrations.RemoveField(
            model_name='card',
            name='yuyu_tei',
        ),
        migrations.AddField(
            model_name='alternateart',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
