# Generated by Django 3.1.2 on 2021-04-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0063_auto_20210330_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effect',
            name='effect_keyword_int_2',
        ),
    ]
